import babelParser from "@babel/eslint-parser";
import globals from "globals"

export default [
    {
        files: ["**/*.js"],
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
                ...globals.jest,
            },
            parser: babelParser,
            parserOptions: {
                requireConfigFile: false,
                babelOptions: {
                    parserOpts: {
                        plugins: ["classProperties", ["decorators", { "decoratorsBeforeExport": false }]],
                    },
                },
            },
        },
        rules: {
            semi: "error",
            "array-callback-return": "error",
            "arrow-body-style": ["error", "as-needed"],
            "block-scoped-var": "error",
            "consistent-return": "warn",
            "constructor-super": "error",
            "curly": ["error", "all"],
            "default-case": "error",
            "default-case-last": "error",
            "dot-notation": "error",
            "eqeqeq": ["error", "always"],
            "for-direction": "error",
            "getter-return": "error",
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-async-promise-executor": "error",
            "no-await-in-loop": "error",
            "no-bitwise": "error",
            "no-caller": "error",
            "no-case-declarations": "warn",
            "no-class-assign": "error",
            "no-compare-neg-zero": "error",
            "no-cond-assign": "error",
            "no-const-assign": "error",
            "no-constant-condition": "error",
            "no-constructor-return": "error",
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-delete-var": "error",
            "no-div-regex": "error",
            "no-dupe-args": "error",
            "no-dupe-class-members": "error",
            "no-dupe-else-if": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-duplicate-imports": "error",
            "no-else-return": "warn",
            "no-empty": "error",
            "no-empty-character-class": "error",
            "no-empty-function": "error",
            "no-empty-pattern": "error",
            "no-empty-static-block": "warn",
            "no-eq-null": "error",
            "no-eval": "warn",
            "no-ex-assign": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-boolean-cast": "warn",
            "no-fallthrough": "error",
            "no-func-assign": "error",
            "no-global-assign": "error",
            "no-implied-eval": "error",
            "no-import-assign": "error",
            "no-inner-declarations": "warn",
            "no-invalid-regexp": "error",
            "no-invalid-this": "error",
            "no-irregular-whitespace": "error",
            "no-iterator": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-loop-func": "error",
            "no-loss-of-precision": "error",
            "no-magic-numbers": [
                "error",
                {
                    "ignoreArrayIndexes": true,
                    "ignoreClassFieldInitialValues": true
                },
            ],
            "no-misleading-character-class": "error",
            "no-multi-assign": "error",
            "no-multi-str": "error",
            "no-negated-condition": "warn",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-symbol": "error",
            "no-new-wrappers": "error",
            "no-nonoctal-decimal-escape": "error",
            "no-obj-calls": "error",
            "no-object-constructor": "error",
            "no-octal": "error",
            "no-octal-escape": "error",
            "no-promise-executor-return": "warn",
            "no-prototype-builtins": "error",
            "no-redeclare": "error",
            "no-regex-spaces": "warn",
            "no-return-assign": "error",
            "no-script-url": "error",
            "no-self-assign": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-setter-return": "error",
            "no-shadow-restricted-names": "error",
            "no-sparse-arrays": "error",
            "no-template-curly-in-string": "warn",
            "no-this-before-super": "error",
            "no-throw-literal": "error",
            "no-undef": "error",
            "no-undef-init": "error",
            "no-unexpected-multiline": "error",
            "no-unmodified-loop-condition": "warn",
            "no-unneeded-ternary": "warn",
            "no-unreachable": "error",
            "no-unsafe-finally": "error",
            "no-unsafe-negation": "error",
            "no-unsafe-optional-chaining": "error",
            "no-unused-labels": "error",
            "no-unused-vars": "error",
            "no-use-before-define": "error",
            "no-useless-assignment": "error",
            "no-useless-backreference": "error",
            "no-useless-call": "error",
            "no-useless-catch": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-useless-escape": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "warn",
            "no-void": "error",
            "no-with": "error",
            "prefer-const": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "require-atomic-updates": "error",
            "require-yield": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
        },
    },
];